kind: Secret
apiVersion: v1
metadata:
  name: controller-edb-02-admin-password
  namespace: aap-24-dr
data:
  password: <password_can_be_generated_by_deploying_a_default_AAP_instance_then_copying_it>
type: Opaque

